/**
 * Central Article Registry for How to Attract Birds Blog
 *
 * IMPORTANT:
 * This file is currently used as the article data source for
 * the Blog Landing Page.
 *
 * Do not change the variable name "ARTICLES" unless the Blog
 * rendering JavaScript is updated at the same time.
 *
 * To publish a new post manually, add a new object to this array.
 *
 * Note:
 * This registry can later be automatically generated by the
 * build process. Until that system is fully implemented,
 * keep the existing article data intact.
 */

const ARTICLES = [
    {
        id: "how-to-attract-northern-cardinals",
        title: "How to Attract Northern Cardinals to Your Yard: 5 Proven Steps",
        category: "Species Guides",
        excerpt: "Discover the best seeds, feeder styles, and native cover plants required to bring vibrant red cardinals to your backyard year-round.",
        url: "how-to-attract-northern-cardinals.html",
        image: "images/cardinals.jpg",
        date: "August 16, 2026",
        readTime: "5 min read",
        featured: true
    },
    {
        id: "ultimate-hummingbird-nectar-guide",
        title: "The Ultimate Homemade Hummingbird Nectar Recipe & Feeder Guide",
        category: "Feeders & Nectar",
        excerpt: "Learn why the standard 4:1 water-to-sugar ratio is the safest fuel for hummingbirds, and why red dye and honey should always be avoided.",
        url: "/blog/ultimate-hummingbird-nectar-guide.html",
        image: "/blog/images/hummingbird-feeder.jpg",
        date: "August 10, 2026",
        readTime: "4 min read",
        featured: false
    },
    {
        id: "winter-bird-feeding-strategies",
        title: "Winter Bird Feeding Strategies: High-Calorie Foods for Freezing Weather",
        category: "Seasonal Care",
        excerpt: "How to supply suet, peanuts, heated bird baths, and sunflower seeds to support overwintering songbirds during severe cold snaps.",
        url: "/blog/winter-bird-feeding-strategies.html",
        image: "/blog/images/winter-birds.jpg",
        date: "August 02, 2026",
        readTime: "6 min read",
        featured: false
    },
    {
        id: "top-native-trees-for-backyard-birds",
        title: "Top 7 Native North American Trees That Attract the Most Birds",
        category: "Habitat & Plants",
        excerpt: "Why native oaks, serviceberries, and dogwoods outperform non-native ornamental trees in supporting caterpillars and nesting songbirds.",
        url: "/blog/top-native-trees-for-backyard-birds.html",
        image: "/blog/images/native-trees.jpg",
        date: "July 24, 2026",
        readTime: "7 min read",
        featured: false
    },
    {
        id: "how-to-clean-bird-baths-prevent-disease",
        title: "How to Clean and Maintain Bird Baths to Prevent Avian Disease",
        category: "Water & Hygiene",
        excerpt: "Step-by-step cleaning protocols and placement strategies to keep backyard water fresh, mosquito-free, and safe for wild birds.",
        url: "/blog/how-to-clean-bird-baths-prevent-disease.html",
        image: "/blog/images/bird-bath-care.jpg",
        date: "July 15, 2026",
        readTime: "4 min read",
        featured: false
    }
];
